### ISSUE TITLE
question: do you know the macos release url??

### ISSUE THREAD

**Issue by joaofnds** [joelsgp-pkgbuild/jetbrains-fleet#1]
and where did you get the linux URL?

**Comment by irismessage** [comment]
I don't know the mac one but I found this url by installing using toolbox, going to .local/share/JetBrains/Toolbox/logs/toolbox.log and searching for urls. If you can find your log location you can find the appropriate url

**Comment by joaofnds** [comment]
Found it there, thanks!

https://download-cdn.jetbrains.com/fleet/installers/macos_aarch64/Fleet-1.9.231-aarch64.dmg
